# basic options
title: The SITUATION
author: Thuo
email: david_thuo@yahoo.com
description: DNA and DNA tales
twitter_username: ThuoPap
github_username:  Dthuo

# Build settings
markdown: kramdown
theme: minima











